# Generated by Django 3.2.15 on 2022-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='var1',
        ),
        migrations.AddField(
            model_name='data',
            name='var',
            field=models.CharField(blank=True, max_length=255, verbose_name='Editable Variable'),
        ),
    ]
